/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiCronNurtureRouteImport } from './routes/api/cron/nurture'
import { Route as ApiCronRecurringScanRouteImport } from './routes/api/cron/recurring-scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronNurtureRoute = ApiCronNurtureRouteImport.update({
  id: '/api/cron/nurture',
  path: '/api/cron/nurture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRecurringScanRoute = ApiCronRecurringScanRouteImport.update({
  id: '/api/cron/recurring-scan',
  path: '/api/cron/recurring-scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/snapshot': typeof SnapshotRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog': typeof BlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/cron/nurture': typeof ApiCronNurtureRoute
  '/api/cron/recurring-scan': typeof ApiCronRecurringScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/snapshot': typeof SnapshotRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog': typeof BlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/cron/nurture': typeof ApiCronNurtureRoute
  '/api/cron/recurring-scan': typeof ApiCronRecurringScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/snapshot': typeof SnapshotRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog': typeof BlogRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/api/cron/nurture': typeof ApiCronNurtureRoute
  '/api/cron/recurring-scan': typeof ApiCronRecurringScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/snapshot' | '/privacy' | '/terms' | '/blog' | '/blog/$slug' | '/api/cron/nurture' | '/api/cron/recurring-scan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/snapshot' | '/privacy' | '/terms' | '/blog' | '/blog/$slug' | '/api/cron/nurture' | '/api/cron/recurring-scan'
  id: '__root__' | '/' | '/snapshot' | '/privacy' | '/terms' | '/blog' | '/blog/$slug' | '/api/cron/nurture' | '/api/cron/recurring-scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SnapshotRoute: typeof SnapshotRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  BlogRoute: typeof BlogRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ApiCronNurtureRoute: typeof ApiCronNurtureRoute
  ApiCronRecurringScanRoute: typeof ApiCronRecurringScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/nurture': {
      id: '/api/cron/nurture'
      path: '/api/cron/nurture'
      fullPath: '/api/cron/nurture'
      preLoaderRoute: typeof ApiCronNurtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/recurring-scan': {
      id: '/api/cron/recurring-scan'
      path: '/api/cron/recurring-scan'
      fullPath: '/api/cron/recurring-scan'
      preLoaderRoute: typeof ApiCronRecurringScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SnapshotRoute: SnapshotRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  BlogRoute: BlogRoute,
  BlogSlugRoute: BlogSlugRoute,
  ApiCronNurtureRoute: ApiCronNurtureRoute,
  ApiCronRecurringScanRoute: ApiCronRecurringScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
